spring:
  datasource:
    url: jdbc:mysql://localhost:3306/online_music
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  devtools:
    restart:
      enabled: true # 开启 hot swapping
      log-condition-evaluation-delta: true  #  Whether to log the condition evaluation delta upon restart.
    #      additional-paths:
    #        - resources/static/**
    livereload:
      enabled: true # 开启资源重载